# Generated by Django 5.0.9 on 2024-11-16 11:48
# Version 2.0: add TrigramExtension operation: This operation executes
# the SQL statement `CREATE EXTENSION pg_trgm` to create the extension in PostgreSQL.
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_post_tags"),
    ]

    operations = [
        TrigramExtension(),
    ]
